name: 新特性提交
description: 如果您有好的想法
labels: ["Feature"  ]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我充分理解提交的建议可能无法所有启动器作者参与，并尊重所有启动器开发者的选择"
    - label: "我确认在Issues列表中并无其他人已经提出过与此问题相同或相似的问题"
      required: true
- type: dropdown
  id: "user-type"
  attributes:
    label: "您是什么类型的用户"
    description: "请认真填写该选项"
    options:
    - 启动器作者
    - 第三方网站管理/负责人
    - 服务器管理
    - 普通用户
    - 其他
  validations:
    required: true
- type: textarea
  id: "content"
  attributes:
    label: 请简单的说一下您的想法
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "whydothat"
  attributes:
    label: 它能解决什么样的问题/带来什么样的帮助
    description: "简而言之，为什么这个功能是必要的"
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-4"
  attributes:
    label: 期望的结果
    placeholder: "-（请在这里回答）-"
  validations:
    required: true
- type: textarea
  id: "yml-5"
  attributes:
    label: 是否有对这个方案的相关链接？
    description: "例如相关SDK的链接、开发文档等"
    placeholder: "-（请在这里回答，若没有可留空）-"
  validations:
    required: false
- type: textarea
  id: "yml-8"
  attributes:
    label: 附注
    placeholder: "-（请在这里回答）-"
